/* Auto-generated by snesrecomp v2 tools/v2_sync_funcs_h.py.
 * Do NOT hand-edit. Every recompiled function takes a
 * CpuState* and mutates it in place — no return values, no
 * register-packed structs. Drop custom typedefs (HdmaPtrs,
 * PairU8, OwHvPos, CollInfo, ExtCollOut, CheckPlatformCollRet,
 * CalcTiltPlatformArgs) — all v1 ABI fiction, gone.
 *
 * Per-(m, x) variants: every named function is declared in
 * five forms so cross-bank generated calls can reference any
 * variant without a side-car header dependency. Unused
 * variants are harmless (C only flags undefined REFERENCES,
 * not undefined DECLARATIONS at link time).
 */
#pragma once

#include "cpu_state.h"

/* 151 functions across all banks (5 decls each). */

void Reset_Entry(CpuState *cpu);  /* $00:8000 alias */
RecompReturn Reset_Entry_M0X0(CpuState *cpu);
RecompReturn Reset_Entry_M0X1(CpuState *cpu);
RecompReturn Reset_Entry_M1X0(CpuState *cpu);
RecompReturn Reset_Entry_M1X1(CpuState *cpu);
void Abort_Handler(CpuState *cpu);  /* $00:8000 alias */
RecompReturn Abort_Handler_M0X0(CpuState *cpu);
RecompReturn Abort_Handler_M0X1(CpuState *cpu);
RecompReturn Abort_Handler_M1X0(CpuState *cpu);
RecompReturn Abort_Handler_M1X1(CpuState *cpu);
void VBlank_Wait(CpuState *cpu);  /* $00:804D alias */
RecompReturn VBlank_Wait_M0X0(CpuState *cpu);
RecompReturn VBlank_Wait_M0X1(CpuState *cpu);
RecompReturn VBlank_Wait_M1X0(CpuState *cpu);
RecompReturn VBlank_Wait_M1X1(CpuState *cpu);
void MainLoop(CpuState *cpu);  /* $00:805C alias */
RecompReturn MainLoop_M0X0(CpuState *cpu);
RecompReturn MainLoop_M0X1(CpuState *cpu);
RecompReturn MainLoop_M1X0(CpuState *cpu);
RecompReturn MainLoop_M1X1(CpuState *cpu);
void Init_Hardware(CpuState *cpu);  /* $00:8061 alias */
RecompReturn Init_Hardware_M0X0(CpuState *cpu);
RecompReturn Init_Hardware_M0X1(CpuState *cpu);
RecompReturn Init_Hardware_M1X0(CpuState *cpu);
RecompReturn Init_Hardware_M1X1(CpuState *cpu);
void NMI_Handler(CpuState *cpu);  /* $00:80B2 alias */
RecompReturn NMI_Handler_M0X0(CpuState *cpu);
RecompReturn NMI_Handler_M0X1(CpuState *cpu);
RecompReturn NMI_Handler_M1X0(CpuState *cpu);
RecompReturn NMI_Handler_M1X1(CpuState *cpu);
void IRQ_Handler(CpuState *cpu);  /* $00:8210 alias */
RecompReturn IRQ_Handler_M0X0(CpuState *cpu);
RecompReturn IRQ_Handler_M0X1(CpuState *cpu);
RecompReturn IRQ_Handler_M1X0(CpuState *cpu);
RecompReturn IRQ_Handler_M1X1(CpuState *cpu);
void COP_Handler(CpuState *cpu);  /* $00:8211 alias */
RecompReturn COP_Handler_M0X0(CpuState *cpu);
RecompReturn COP_Handler_M0X1(CpuState *cpu);
RecompReturn COP_Handler_M1X0(CpuState *cpu);
RecompReturn COP_Handler_M1X1(CpuState *cpu);
void BRK_Handler(CpuState *cpu);  /* $00:8239 alias */
RecompReturn BRK_Handler_M0X0(CpuState *cpu);
RecompReturn BRK_Handler_M0X1(CpuState *cpu);
RecompReturn BRK_Handler_M1X0(CpuState *cpu);
RecompReturn BRK_Handler_M1X1(CpuState *cpu);
void City_Update(CpuState *cpu);  /* $01:8000 alias */
RecompReturn City_Update_M0X0(CpuState *cpu);
RecompReturn City_Update_M0X1(CpuState *cpu);
RecompReturn City_Update_M1X0(CpuState *cpu);
RecompReturn City_Update_M1X1(CpuState *cpu);
void Zone_Update(CpuState *cpu);  /* $01:8500 alias */
RecompReturn Zone_Update_M0X0(CpuState *cpu);
RecompReturn Zone_Update_M0X1(CpuState *cpu);
RecompReturn Zone_Update_M1X0(CpuState *cpu);
RecompReturn Zone_Update_M1X1(CpuState *cpu);
void Traffic_Update(CpuState *cpu);  /* $01:8800 alias */
RecompReturn Traffic_Update_M0X0(CpuState *cpu);
RecompReturn Traffic_Update_M0X1(CpuState *cpu);
RecompReturn Traffic_Update_M1X0(CpuState *cpu);
RecompReturn Traffic_Update_M1X1(CpuState *cpu);
void Power_Update(CpuState *cpu);  /* $01:8A00 alias */
RecompReturn Power_Update_M0X0(CpuState *cpu);
RecompReturn Power_Update_M0X1(CpuState *cpu);
RecompReturn Power_Update_M1X0(CpuState *cpu);
RecompReturn Power_Update_M1X1(CpuState *cpu);
void Water_Update(CpuState *cpu);  /* $01:8C00 alias */
RecompReturn Water_Update_M0X0(CpuState *cpu);
RecompReturn Water_Update_M0X1(CpuState *cpu);
RecompReturn Water_Update_M1X0(CpuState *cpu);
RecompReturn Water_Update_M1X1(CpuState *cpu);
void Disaster_Update(CpuState *cpu);  /* $01:8E00 alias */
RecompReturn Disaster_Update_M0X0(CpuState *cpu);
RecompReturn Disaster_Update_M0X1(CpuState *cpu);
RecompReturn Disaster_Update_M1X0(CpuState *cpu);
RecompReturn Disaster_Update_M1X1(CpuState *cpu);
void Budget_Calc(CpuState *cpu);  /* $01:9000 alias */
RecompReturn Budget_Calc_M0X0(CpuState *cpu);
RecompReturn Budget_Calc_M0X1(CpuState *cpu);
RecompReturn Budget_Calc_M1X0(CpuState *cpu);
RecompReturn Budget_Calc_M1X1(CpuState *cpu);
void Tax_Update(CpuState *cpu);  /* $01:9100 alias */
RecompReturn Tax_Update_M0X0(CpuState *cpu);
RecompReturn Tax_Update_M0X1(CpuState *cpu);
RecompReturn Tax_Update_M1X0(CpuState *cpu);
RecompReturn Tax_Update_M1X1(CpuState *cpu);
void Population_Update(CpuState *cpu);  /* $01:9200 alias */
RecompReturn Population_Update_M0X0(CpuState *cpu);
RecompReturn Population_Update_M0X1(CpuState *cpu);
RecompReturn Population_Update_M1X0(CpuState *cpu);
RecompReturn Population_Update_M1X1(CpuState *cpu);
void RCI_Update(CpuState *cpu);  /* $01:9300 alias */
RecompReturn RCI_Update_M0X0(CpuState *cpu);
RecompReturn RCI_Update_M0X1(CpuState *cpu);
RecompReturn RCI_Update_M1X0(CpuState *cpu);
RecompReturn RCI_Update_M1X1(CpuState *cpu);
void Meteor_Spawn(CpuState *cpu);  /* $01:9400 alias */
RecompReturn Meteor_Spawn_M0X0(CpuState *cpu);
RecompReturn Meteor_Spawn_M0X1(CpuState *cpu);
RecompReturn Meteor_Spawn_M1X0(CpuState *cpu);
RecompReturn Meteor_Spawn_M1X1(CpuState *cpu);
void Monster_Spawn(CpuState *cpu);  /* $01:9500 alias */
RecompReturn Monster_Spawn_M0X0(CpuState *cpu);
RecompReturn Monster_Spawn_M0X1(CpuState *cpu);
RecompReturn Monster_Spawn_M1X0(CpuState *cpu);
RecompReturn Monster_Spawn_M1X1(CpuState *cpu);
void Earthquake_Trigger(CpuState *cpu);  /* $01:9600 alias */
RecompReturn Earthquake_Trigger_M0X0(CpuState *cpu);
RecompReturn Earthquake_Trigger_M0X1(CpuState *cpu);
RecompReturn Earthquake_Trigger_M1X0(CpuState *cpu);
RecompReturn Earthquake_Trigger_M1X1(CpuState *cpu);
void Fire_Update(CpuState *cpu);  /* $01:9700 alias */
RecompReturn Fire_Update_M0X0(CpuState *cpu);
RecompReturn Fire_Update_M0X1(CpuState *cpu);
RecompReturn Fire_Update_M1X0(CpuState *cpu);
RecompReturn Fire_Update_M1X1(CpuState *cpu);
void Scenario_Load(CpuState *cpu);  /* $01:9800 alias */
RecompReturn Scenario_Load_M0X0(CpuState *cpu);
RecompReturn Scenario_Load_M0X1(CpuState *cpu);
RecompReturn Scenario_Load_M1X0(CpuState *cpu);
RecompReturn Scenario_Load_M1X1(CpuState *cpu);
void Scenario_Update(CpuState *cpu);  /* $01:9900 alias */
RecompReturn Scenario_Update_M0X0(CpuState *cpu);
RecompReturn Scenario_Update_M0X1(CpuState *cpu);
RecompReturn Scenario_Update_M1X0(CpuState *cpu);
RecompReturn Scenario_Update_M1X1(CpuState *cpu);
void Res_D01_TL(CpuState *cpu);  /* $02:03AC alias */
RecompReturn Res_D01_TL_M0X0(CpuState *cpu);
RecompReturn Res_D01_TL_M0X1(CpuState *cpu);
RecompReturn Res_D01_TL_M1X0(CpuState *cpu);
RecompReturn Res_D01_TL_M1X1(CpuState *cpu);
void Res_D01_TR(CpuState *cpu);  /* $02:03AD alias */
RecompReturn Res_D01_TR_M0X0(CpuState *cpu);
RecompReturn Res_D01_TR_M0X1(CpuState *cpu);
RecompReturn Res_D01_TR_M1X0(CpuState *cpu);
RecompReturn Res_D01_TR_M1X1(CpuState *cpu);
void Res_D01_BL(CpuState *cpu);  /* $02:03AE alias */
RecompReturn Res_D01_BL_M0X0(CpuState *cpu);
RecompReturn Res_D01_BL_M0X1(CpuState *cpu);
RecompReturn Res_D01_BL_M1X0(CpuState *cpu);
RecompReturn Res_D01_BL_M1X1(CpuState *cpu);
void Res_D01_BR(CpuState *cpu);  /* $02:03AF alias */
RecompReturn Res_D01_BR_M0X0(CpuState *cpu);
RecompReturn Res_D01_BR_M0X1(CpuState *cpu);
RecompReturn Res_D01_BR_M1X0(CpuState *cpu);
RecompReturn Res_D01_BR_M1X1(CpuState *cpu);
void Res_D23_TL(CpuState *cpu);  /* $02:03B0 alias */
RecompReturn Res_D23_TL_M0X0(CpuState *cpu);
RecompReturn Res_D23_TL_M0X1(CpuState *cpu);
RecompReturn Res_D23_TL_M1X0(CpuState *cpu);
RecompReturn Res_D23_TL_M1X1(CpuState *cpu);
void Res_D23_TR(CpuState *cpu);  /* $02:03B1 alias */
RecompReturn Res_D23_TR_M0X0(CpuState *cpu);
RecompReturn Res_D23_TR_M0X1(CpuState *cpu);
RecompReturn Res_D23_TR_M1X0(CpuState *cpu);
RecompReturn Res_D23_TR_M1X1(CpuState *cpu);
void Res_D23_BL(CpuState *cpu);  /* $02:03B2 alias */
RecompReturn Res_D23_BL_M0X0(CpuState *cpu);
RecompReturn Res_D23_BL_M0X1(CpuState *cpu);
RecompReturn Res_D23_BL_M1X0(CpuState *cpu);
RecompReturn Res_D23_BL_M1X1(CpuState *cpu);
void Res_D23_BR(CpuState *cpu);  /* $02:03B3 alias */
RecompReturn Res_D23_BR_M0X0(CpuState *cpu);
RecompReturn Res_D23_BR_M0X1(CpuState *cpu);
RecompReturn Res_D23_BR_M1X0(CpuState *cpu);
RecompReturn Res_D23_BR_M1X1(CpuState *cpu);
void Res_D23_TR2(CpuState *cpu);  /* $02:03B4 alias */
RecompReturn Res_D23_TR2_M0X0(CpuState *cpu);
RecompReturn Res_D23_TR2_M0X1(CpuState *cpu);
RecompReturn Res_D23_TR2_M1X0(CpuState *cpu);
RecompReturn Res_D23_TR2_M1X1(CpuState *cpu);
void Res_D23_BL2(CpuState *cpu);  /* $02:03B5 alias */
RecompReturn Res_D23_BL2_M0X0(CpuState *cpu);
RecompReturn Res_D23_BL2_M0X1(CpuState *cpu);
RecompReturn Res_D23_BL2_M1X0(CpuState *cpu);
RecompReturn Res_D23_BL2_M1X1(CpuState *cpu);
void Res_D23_BR2(CpuState *cpu);  /* $02:03B5 alias */
RecompReturn Res_D23_BR2_M0X0(CpuState *cpu);
RecompReturn Res_D23_BR2_M0X1(CpuState *cpu);
RecompReturn Res_D23_BR2_M1X0(CpuState *cpu);
RecompReturn Res_D23_BR2_M1X1(CpuState *cpu);
void Res_D45_C(CpuState *cpu);  /* $02:03C0 alias */
RecompReturn Res_D45_C_M0X0(CpuState *cpu);
RecompReturn Res_D45_C_M0X1(CpuState *cpu);
RecompReturn Res_D45_C_M1X0(CpuState *cpu);
RecompReturn Res_D45_C_M1X1(CpuState *cpu);
void Res_D45_TL(CpuState *cpu);  /* $02:03C1 alias */
RecompReturn Res_D45_TL_M0X0(CpuState *cpu);
RecompReturn Res_D45_TL_M0X1(CpuState *cpu);
RecompReturn Res_D45_TL_M1X0(CpuState *cpu);
RecompReturn Res_D45_TL_M1X1(CpuState *cpu);
void Res_D45_TR(CpuState *cpu);  /* $02:03C2 alias */
RecompReturn Res_D45_TR_M0X0(CpuState *cpu);
RecompReturn Res_D45_TR_M0X1(CpuState *cpu);
RecompReturn Res_D45_TR_M1X0(CpuState *cpu);
RecompReturn Res_D45_TR_M1X1(CpuState *cpu);
void Res_D45_BL(CpuState *cpu);  /* $02:03C3 alias */
RecompReturn Res_D45_BL_M0X0(CpuState *cpu);
RecompReturn Res_D45_BL_M0X1(CpuState *cpu);
RecompReturn Res_D45_BL_M1X0(CpuState *cpu);
RecompReturn Res_D45_BL_M1X1(CpuState *cpu);
void Res_D45_BR(CpuState *cpu);  /* $02:03C4 alias */
RecompReturn Res_D45_BR_M0X0(CpuState *cpu);
RecompReturn Res_D45_BR_M0X1(CpuState *cpu);
RecompReturn Res_D45_BR_M1X0(CpuState *cpu);
RecompReturn Res_D45_BR_M1X1(CpuState *cpu);
void Res_D45_T(CpuState *cpu);  /* $02:03C5 alias */
RecompReturn Res_D45_T_M0X0(CpuState *cpu);
RecompReturn Res_D45_T_M0X1(CpuState *cpu);
RecompReturn Res_D45_T_M1X0(CpuState *cpu);
RecompReturn Res_D45_T_M1X1(CpuState *cpu);
void Res_D45_B(CpuState *cpu);  /* $02:03C6 alias */
RecompReturn Res_D45_B_M0X0(CpuState *cpu);
RecompReturn Res_D45_B_M0X1(CpuState *cpu);
RecompReturn Res_D45_B_M1X0(CpuState *cpu);
RecompReturn Res_D45_B_M1X1(CpuState *cpu);
void Res_D45_L(CpuState *cpu);  /* $02:03C7 alias */
RecompReturn Res_D45_L_M0X0(CpuState *cpu);
RecompReturn Res_D45_L_M0X1(CpuState *cpu);
RecompReturn Res_D45_L_M1X0(CpuState *cpu);
RecompReturn Res_D45_L_M1X1(CpuState *cpu);
void Res_D45_R(CpuState *cpu);  /* $02:03C7 alias */
RecompReturn Res_D45_R_M0X0(CpuState *cpu);
RecompReturn Res_D45_R_M0X1(CpuState *cpu);
RecompReturn Res_D45_R_M1X0(CpuState *cpu);
RecompReturn Res_D45_R_M1X1(CpuState *cpu);
void Com_D01_TL(CpuState *cpu);  /* $02:03D0 alias */
RecompReturn Com_D01_TL_M0X0(CpuState *cpu);
RecompReturn Com_D01_TL_M0X1(CpuState *cpu);
RecompReturn Com_D01_TL_M1X0(CpuState *cpu);
RecompReturn Com_D01_TL_M1X1(CpuState *cpu);
void Com_D45_TL(CpuState *cpu);  /* $02:03D0 alias */
RecompReturn Com_D45_TL_M0X0(CpuState *cpu);
RecompReturn Com_D45_TL_M0X1(CpuState *cpu);
RecompReturn Com_D45_TL_M1X0(CpuState *cpu);
RecompReturn Com_D45_TL_M1X1(CpuState *cpu);
void Mayor_House_TL(CpuState *cpu);  /* $02:03D0 alias */
RecompReturn Mayor_House_TL_M0X0(CpuState *cpu);
RecompReturn Mayor_House_TL_M0X1(CpuState *cpu);
RecompReturn Mayor_House_TL_M1X0(CpuState *cpu);
RecompReturn Mayor_House_TL_M1X1(CpuState *cpu);
void Com_D01_TR(CpuState *cpu);  /* $02:03D1 alias */
RecompReturn Com_D01_TR_M0X0(CpuState *cpu);
RecompReturn Com_D01_TR_M0X1(CpuState *cpu);
RecompReturn Com_D01_TR_M1X0(CpuState *cpu);
RecompReturn Com_D01_TR_M1X1(CpuState *cpu);
void Com_D45_TR(CpuState *cpu);  /* $02:03D1 alias */
RecompReturn Com_D45_TR_M0X0(CpuState *cpu);
RecompReturn Com_D45_TR_M0X1(CpuState *cpu);
RecompReturn Com_D45_TR_M1X0(CpuState *cpu);
RecompReturn Com_D45_TR_M1X1(CpuState *cpu);
void Mayor_House_TR(CpuState *cpu);  /* $02:03D1 alias */
RecompReturn Mayor_House_TR_M0X0(CpuState *cpu);
RecompReturn Mayor_House_TR_M0X1(CpuState *cpu);
RecompReturn Mayor_House_TR_M1X0(CpuState *cpu);
RecompReturn Mayor_House_TR_M1X1(CpuState *cpu);
void Mayor_House_BL(CpuState *cpu);  /* $02:03D2 alias */
RecompReturn Mayor_House_BL_M0X0(CpuState *cpu);
RecompReturn Mayor_House_BL_M0X1(CpuState *cpu);
RecompReturn Mayor_House_BL_M1X0(CpuState *cpu);
RecompReturn Mayor_House_BL_M1X1(CpuState *cpu);
void Com_D01_BL(CpuState *cpu);  /* $02:03E0 alias */
RecompReturn Com_D01_BL_M0X0(CpuState *cpu);
RecompReturn Com_D01_BL_M0X1(CpuState *cpu);
RecompReturn Com_D01_BL_M1X0(CpuState *cpu);
RecompReturn Com_D01_BL_M1X1(CpuState *cpu);
void Com_D23_TL(CpuState *cpu);  /* $02:03E0 alias */
RecompReturn Com_D23_TL_M0X0(CpuState *cpu);
RecompReturn Com_D23_TL_M0X1(CpuState *cpu);
RecompReturn Com_D23_TL_M1X0(CpuState *cpu);
RecompReturn Com_D23_TL_M1X1(CpuState *cpu);
void Com_D45_BL(CpuState *cpu);  /* $02:03E0 alias */
RecompReturn Com_D45_BL_M0X0(CpuState *cpu);
RecompReturn Com_D45_BL_M0X1(CpuState *cpu);
RecompReturn Com_D45_BL_M1X0(CpuState *cpu);
RecompReturn Com_D45_BL_M1X1(CpuState *cpu);
void Power_Nuclear_TL(CpuState *cpu);  /* $02:03E0 alias */
RecompReturn Power_Nuclear_TL_M0X0(CpuState *cpu);
RecompReturn Power_Nuclear_TL_M0X1(CpuState *cpu);
RecompReturn Power_Nuclear_TL_M1X0(CpuState *cpu);
RecompReturn Power_Nuclear_TL_M1X1(CpuState *cpu);
void Stadium_TL(CpuState *cpu);  /* $02:03E0 alias */
RecompReturn Stadium_TL_M0X0(CpuState *cpu);
RecompReturn Stadium_TL_M0X1(CpuState *cpu);
RecompReturn Stadium_TL_M1X0(CpuState *cpu);
RecompReturn Stadium_TL_M1X1(CpuState *cpu);
void Com_D01_BR(CpuState *cpu);  /* $02:03E1 alias */
RecompReturn Com_D01_BR_M0X0(CpuState *cpu);
RecompReturn Com_D01_BR_M0X1(CpuState *cpu);
RecompReturn Com_D01_BR_M1X0(CpuState *cpu);
RecompReturn Com_D01_BR_M1X1(CpuState *cpu);
void Com_D23_TR(CpuState *cpu);  /* $02:03E1 alias */
RecompReturn Com_D23_TR_M0X0(CpuState *cpu);
RecompReturn Com_D23_TR_M0X1(CpuState *cpu);
RecompReturn Com_D23_TR_M1X0(CpuState *cpu);
RecompReturn Com_D23_TR_M1X1(CpuState *cpu);
void Com_D45_BR(CpuState *cpu);  /* $02:03E1 alias */
RecompReturn Com_D45_BR_M0X0(CpuState *cpu);
RecompReturn Com_D45_BR_M0X1(CpuState *cpu);
RecompReturn Com_D45_BR_M1X0(CpuState *cpu);
RecompReturn Com_D45_BR_M1X1(CpuState *cpu);
void Power_Nuclear_TR(CpuState *cpu);  /* $02:03E1 alias */
RecompReturn Power_Nuclear_TR_M0X0(CpuState *cpu);
RecompReturn Power_Nuclear_TR_M0X1(CpuState *cpu);
RecompReturn Power_Nuclear_TR_M1X0(CpuState *cpu);
RecompReturn Power_Nuclear_TR_M1X1(CpuState *cpu);
void Stadium_TR(CpuState *cpu);  /* $02:03E1 alias */
RecompReturn Stadium_TR_M0X0(CpuState *cpu);
RecompReturn Stadium_TR_M0X1(CpuState *cpu);
RecompReturn Stadium_TR_M1X0(CpuState *cpu);
RecompReturn Stadium_TR_M1X1(CpuState *cpu);
void Com_D23_BL(CpuState *cpu);  /* $02:03E2 alias */
RecompReturn Com_D23_BL_M0X0(CpuState *cpu);
RecompReturn Com_D23_BL_M0X1(CpuState *cpu);
RecompReturn Com_D23_BL_M1X0(CpuState *cpu);
RecompReturn Com_D23_BL_M1X1(CpuState *cpu);
void Power_Nuclear_BL(CpuState *cpu);  /* $02:03E2 alias */
RecompReturn Power_Nuclear_BL_M0X0(CpuState *cpu);
RecompReturn Power_Nuclear_BL_M0X1(CpuState *cpu);
RecompReturn Power_Nuclear_BL_M1X0(CpuState *cpu);
RecompReturn Power_Nuclear_BL_M1X1(CpuState *cpu);
void Stadium_BL(CpuState *cpu);  /* $02:03E2 alias */
RecompReturn Stadium_BL_M0X0(CpuState *cpu);
RecompReturn Stadium_BL_M0X1(CpuState *cpu);
RecompReturn Stadium_BL_M1X0(CpuState *cpu);
RecompReturn Stadium_BL_M1X1(CpuState *cpu);
void Airport_BL(CpuState *cpu);  /* $02:03E2 alias */
RecompReturn Airport_BL_M0X0(CpuState *cpu);
RecompReturn Airport_BL_M0X1(CpuState *cpu);
RecompReturn Airport_BL_M1X0(CpuState *cpu);
RecompReturn Airport_BL_M1X1(CpuState *cpu);
void Com_D23_BR(CpuState *cpu);  /* $02:03E3 alias */
RecompReturn Com_D23_BR_M0X0(CpuState *cpu);
RecompReturn Com_D23_BR_M0X1(CpuState *cpu);
RecompReturn Com_D23_BR_M1X0(CpuState *cpu);
RecompReturn Com_D23_BR_M1X1(CpuState *cpu);
void Airport_TL(CpuState *cpu);  /* $02:03E4 alias */
RecompReturn Airport_TL_M0X0(CpuState *cpu);
RecompReturn Airport_TL_M0X1(CpuState *cpu);
RecompReturn Airport_TL_M1X0(CpuState *cpu);
RecompReturn Airport_TL_M1X1(CpuState *cpu);
void Airport_TR(CpuState *cpu);  /* $02:03E5 alias */
RecompReturn Airport_TR_M0X0(CpuState *cpu);
RecompReturn Airport_TR_M0X1(CpuState *cpu);
RecompReturn Airport_TR_M1X0(CpuState *cpu);
RecompReturn Airport_TR_M1X1(CpuState *cpu);
void Seaport_TL(CpuState *cpu);  /* $02:03E8 alias */
RecompReturn Seaport_TL_M0X0(CpuState *cpu);
RecompReturn Seaport_TL_M0X1(CpuState *cpu);
RecompReturn Seaport_TL_M1X0(CpuState *cpu);
RecompReturn Seaport_TL_M1X1(CpuState *cpu);
void Seaport_BL(CpuState *cpu);  /* $02:03EA alias */
RecompReturn Seaport_BL_M0X0(CpuState *cpu);
RecompReturn Seaport_BL_M0X1(CpuState *cpu);
RecompReturn Seaport_BL_M1X0(CpuState *cpu);
RecompReturn Seaport_BL_M1X1(CpuState *cpu);
void Seaport_TR(CpuState *cpu);  /* $02:03ED alias */
RecompReturn Seaport_TR_M0X0(CpuState *cpu);
RecompReturn Seaport_TR_M0X1(CpuState *cpu);
RecompReturn Seaport_TR_M1X0(CpuState *cpu);
RecompReturn Seaport_TR_M1X1(CpuState *cpu);
void Com_D23_TR2(CpuState *cpu);  /* $02:03EF alias */
RecompReturn Com_D23_TR2_M0X0(CpuState *cpu);
RecompReturn Com_D23_TR2_M0X1(CpuState *cpu);
RecompReturn Com_D23_TR2_M1X0(CpuState *cpu);
RecompReturn Com_D23_TR2_M1X1(CpuState *cpu);
void Com_D23_BR2(CpuState *cpu);  /* $02:03EF alias */
RecompReturn Com_D23_BR2_M0X0(CpuState *cpu);
RecompReturn Com_D23_BR2_M0X1(CpuState *cpu);
RecompReturn Com_D23_BR2_M1X0(CpuState *cpu);
RecompReturn Com_D23_BR2_M1X1(CpuState *cpu);
void Power_Nuclear_BR(CpuState *cpu);  /* $02:03EF alias */
RecompReturn Power_Nuclear_BR_M0X0(CpuState *cpu);
RecompReturn Power_Nuclear_BR_M0X1(CpuState *cpu);
RecompReturn Power_Nuclear_BR_M1X0(CpuState *cpu);
RecompReturn Power_Nuclear_BR_M1X1(CpuState *cpu);
void Com_D23_BL2(CpuState *cpu);  /* $02:03F0 alias */
RecompReturn Com_D23_BL2_M0X0(CpuState *cpu);
RecompReturn Com_D23_BL2_M0X1(CpuState *cpu);
RecompReturn Com_D23_BL2_M1X0(CpuState *cpu);
RecompReturn Com_D23_BL2_M1X1(CpuState *cpu);
void Ind_D01_TL(CpuState *cpu);  /* $02:03F0 alias */
RecompReturn Ind_D01_TL_M0X0(CpuState *cpu);
RecompReturn Ind_D01_TL_M0X1(CpuState *cpu);
RecompReturn Ind_D01_TL_M1X0(CpuState *cpu);
RecompReturn Ind_D01_TL_M1X1(CpuState *cpu);
void Ind_D01_TR(CpuState *cpu);  /* $02:03F1 alias */
RecompReturn Ind_D01_TR_M0X0(CpuState *cpu);
RecompReturn Ind_D01_TR_M0X1(CpuState *cpu);
RecompReturn Ind_D01_TR_M1X0(CpuState *cpu);
RecompReturn Ind_D01_TR_M1X1(CpuState *cpu);
void Ind_D23_TR(CpuState *cpu);  /* $02:03F1 alias */
RecompReturn Ind_D23_TR_M0X0(CpuState *cpu);
RecompReturn Ind_D23_TR_M0X1(CpuState *cpu);
RecompReturn Ind_D23_TR_M1X0(CpuState *cpu);
RecompReturn Ind_D23_TR_M1X1(CpuState *cpu);
void Ind_D45_TR(CpuState *cpu);  /* $02:03F1 alias */
RecompReturn Ind_D45_TR_M0X0(CpuState *cpu);
RecompReturn Ind_D45_TR_M0X1(CpuState *cpu);
RecompReturn Ind_D45_TR_M1X0(CpuState *cpu);
RecompReturn Ind_D45_TR_M1X1(CpuState *cpu);
void Power_Coal_TR(CpuState *cpu);  /* $02:03F1 alias */
RecompReturn Power_Coal_TR_M0X0(CpuState *cpu);
RecompReturn Power_Coal_TR_M0X1(CpuState *cpu);
RecompReturn Power_Coal_TR_M1X0(CpuState *cpu);
RecompReturn Power_Coal_TR_M1X1(CpuState *cpu);
void Police_HQ_TR(CpuState *cpu);  /* $02:03F1 alias */
RecompReturn Police_HQ_TR_M0X0(CpuState *cpu);
RecompReturn Police_HQ_TR_M0X1(CpuState *cpu);
RecompReturn Police_HQ_TR_M1X0(CpuState *cpu);
RecompReturn Police_HQ_TR_M1X1(CpuState *cpu);
void Ind_D01_BL(CpuState *cpu);  /* $02:03F2 alias */
RecompReturn Ind_D01_BL_M0X0(CpuState *cpu);
RecompReturn Ind_D01_BL_M0X1(CpuState *cpu);
RecompReturn Ind_D01_BL_M1X0(CpuState *cpu);
RecompReturn Ind_D01_BL_M1X1(CpuState *cpu);
void Ind_D23_BL(CpuState *cpu);  /* $02:03F2 alias */
RecompReturn Ind_D23_BL_M0X0(CpuState *cpu);
RecompReturn Ind_D23_BL_M0X1(CpuState *cpu);
RecompReturn Ind_D23_BL_M1X0(CpuState *cpu);
RecompReturn Ind_D23_BL_M1X1(CpuState *cpu);
void Ind_D45_BL(CpuState *cpu);  /* $02:03F2 alias */
RecompReturn Ind_D45_BL_M0X0(CpuState *cpu);
RecompReturn Ind_D45_BL_M0X1(CpuState *cpu);
RecompReturn Ind_D45_BL_M1X0(CpuState *cpu);
RecompReturn Ind_D45_BL_M1X1(CpuState *cpu);
void Power_Coal_BL(CpuState *cpu);  /* $02:03F2 alias */
RecompReturn Power_Coal_BL_M0X0(CpuState *cpu);
RecompReturn Power_Coal_BL_M0X1(CpuState *cpu);
RecompReturn Power_Coal_BL_M1X0(CpuState *cpu);
RecompReturn Power_Coal_BL_M1X1(CpuState *cpu);
void Ind_D01_BR(CpuState *cpu);  /* $02:03F3 alias */
RecompReturn Ind_D01_BR_M0X0(CpuState *cpu);
RecompReturn Ind_D01_BR_M0X1(CpuState *cpu);
RecompReturn Ind_D01_BR_M1X0(CpuState *cpu);
RecompReturn Ind_D01_BR_M1X1(CpuState *cpu);
void Ind_D23_BR(CpuState *cpu);  /* $02:03F3 alias */
RecompReturn Ind_D23_BR_M0X0(CpuState *cpu);
RecompReturn Ind_D23_BR_M0X1(CpuState *cpu);
RecompReturn Ind_D23_BR_M1X0(CpuState *cpu);
RecompReturn Ind_D23_BR_M1X1(CpuState *cpu);
void Ind_D45_BR(CpuState *cpu);  /* $02:03F3 alias */
RecompReturn Ind_D45_BR_M0X0(CpuState *cpu);
RecompReturn Ind_D45_BR_M0X1(CpuState *cpu);
RecompReturn Ind_D45_BR_M1X0(CpuState *cpu);
RecompReturn Ind_D45_BR_M1X1(CpuState *cpu);
void Power_Coal_BR(CpuState *cpu);  /* $02:03F3 alias */
RecompReturn Power_Coal_BR_M0X0(CpuState *cpu);
RecompReturn Power_Coal_BR_M0X1(CpuState *cpu);
RecompReturn Power_Coal_BR_M1X0(CpuState *cpu);
RecompReturn Power_Coal_BR_M1X1(CpuState *cpu);
void Ind_D23_TL(CpuState *cpu);  /* $02:03F4 alias */
RecompReturn Ind_D23_TL_M0X0(CpuState *cpu);
RecompReturn Ind_D23_TL_M0X1(CpuState *cpu);
RecompReturn Ind_D23_TL_M1X0(CpuState *cpu);
RecompReturn Ind_D23_TL_M1X1(CpuState *cpu);
void Ind_D45_TL(CpuState *cpu);  /* $02:03F4 alias */
RecompReturn Ind_D45_TL_M0X0(CpuState *cpu);
RecompReturn Ind_D45_TL_M0X1(CpuState *cpu);
RecompReturn Ind_D45_TL_M1X0(CpuState *cpu);
RecompReturn Ind_D45_TL_M1X1(CpuState *cpu);
void Power_Coal_TL(CpuState *cpu);  /* $02:03F4 alias */
RecompReturn Power_Coal_TL_M0X0(CpuState *cpu);
RecompReturn Power_Coal_TL_M0X1(CpuState *cpu);
RecompReturn Power_Coal_TL_M1X0(CpuState *cpu);
RecompReturn Power_Coal_TL_M1X1(CpuState *cpu);
void Police_HQ_TL(CpuState *cpu);  /* $02:03F4 alias */
RecompReturn Police_HQ_TL_M0X0(CpuState *cpu);
RecompReturn Police_HQ_TL_M0X1(CpuState *cpu);
RecompReturn Police_HQ_TL_M1X0(CpuState *cpu);
RecompReturn Police_HQ_TL_M1X1(CpuState *cpu);
void Police_HQ_BL(CpuState *cpu);  /* $02:03FA alias */
RecompReturn Police_HQ_BL_M0X0(CpuState *cpu);
RecompReturn Police_HQ_BL_M0X1(CpuState *cpu);
RecompReturn Police_HQ_BL_M1X0(CpuState *cpu);
RecompReturn Police_HQ_BL_M1X1(CpuState *cpu);
void Ind_D23_TR2(CpuState *cpu);  /* $02:03FC alias */
RecompReturn Ind_D23_TR2_M0X0(CpuState *cpu);
RecompReturn Ind_D23_TR2_M0X1(CpuState *cpu);
RecompReturn Ind_D23_TR2_M1X0(CpuState *cpu);
RecompReturn Ind_D23_TR2_M1X1(CpuState *cpu);
void Fire_HQ_TL(CpuState *cpu);  /* $02:03FC alias */
RecompReturn Fire_HQ_TL_M0X0(CpuState *cpu);
RecompReturn Fire_HQ_TL_M0X1(CpuState *cpu);
RecompReturn Fire_HQ_TL_M1X0(CpuState *cpu);
RecompReturn Fire_HQ_TL_M1X1(CpuState *cpu);
void Ind_D23_BL2(CpuState *cpu);  /* $02:03FD alias */
RecompReturn Ind_D23_BL2_M0X0(CpuState *cpu);
RecompReturn Ind_D23_BL2_M0X1(CpuState *cpu);
RecompReturn Ind_D23_BL2_M1X0(CpuState *cpu);
RecompReturn Ind_D23_BL2_M1X1(CpuState *cpu);
void Fire_HQ_TR(CpuState *cpu);  /* $02:03FD alias */
RecompReturn Fire_HQ_TR_M0X0(CpuState *cpu);
RecompReturn Fire_HQ_TR_M0X1(CpuState *cpu);
RecompReturn Fire_HQ_TR_M1X0(CpuState *cpu);
RecompReturn Fire_HQ_TR_M1X1(CpuState *cpu);
void Ind_D23_BR2(CpuState *cpu);  /* $02:03FE alias */
RecompReturn Ind_D23_BR2_M0X0(CpuState *cpu);
RecompReturn Ind_D23_BR2_M0X1(CpuState *cpu);
RecompReturn Ind_D23_BR2_M1X0(CpuState *cpu);
RecompReturn Ind_D23_BR2_M1X1(CpuState *cpu);
void Fire_HQ_BL(CpuState *cpu);  /* $02:03FE alias */
RecompReturn Fire_HQ_BL_M0X0(CpuState *cpu);
RecompReturn Fire_HQ_BL_M0X1(CpuState *cpu);
RecompReturn Fire_HQ_BL_M1X0(CpuState *cpu);
RecompReturn Fire_HQ_BL_M1X1(CpuState *cpu);
void Stadium_BR(CpuState *cpu);  /* $02:043F alias */
RecompReturn Stadium_BR_M0X0(CpuState *cpu);
RecompReturn Stadium_BR_M0X1(CpuState *cpu);
RecompReturn Stadium_BR_M1X0(CpuState *cpu);
RecompReturn Stadium_BR_M1X1(CpuState *cpu);
void Airport_BR(CpuState *cpu);  /* $02:043F alias */
RecompReturn Airport_BR_M0X0(CpuState *cpu);
RecompReturn Airport_BR_M0X1(CpuState *cpu);
RecompReturn Airport_BR_M1X0(CpuState *cpu);
RecompReturn Airport_BR_M1X1(CpuState *cpu);
void Seaport_BR(CpuState *cpu);  /* $02:043F alias */
RecompReturn Seaport_BR_M0X0(CpuState *cpu);
RecompReturn Seaport_BR_M0X1(CpuState *cpu);
RecompReturn Seaport_BR_M1X0(CpuState *cpu);
RecompReturn Seaport_BR_M1X1(CpuState *cpu);
void Police_HQ_BR(CpuState *cpu);  /* $02:043F alias */
RecompReturn Police_HQ_BR_M0X0(CpuState *cpu);
RecompReturn Police_HQ_BR_M0X1(CpuState *cpu);
RecompReturn Police_HQ_BR_M1X0(CpuState *cpu);
RecompReturn Police_HQ_BR_M1X1(CpuState *cpu);
void Fire_HQ_BR(CpuState *cpu);  /* $02:043F alias */
RecompReturn Fire_HQ_BR_M0X0(CpuState *cpu);
RecompReturn Fire_HQ_BR_M0X1(CpuState *cpu);
RecompReturn Fire_HQ_BR_M1X0(CpuState *cpu);
RecompReturn Fire_HQ_BR_M1X1(CpuState *cpu);
void Mayor_House_BR(CpuState *cpu);  /* $02:043F alias */
RecompReturn Mayor_House_BR_M0X0(CpuState *cpu);
RecompReturn Mayor_House_BR_M0X1(CpuState *cpu);
RecompReturn Mayor_House_BR_M1X0(CpuState *cpu);
RecompReturn Mayor_House_BR_M1X1(CpuState *cpu);
void Menu_Main(CpuState *cpu);  /* $03:8000 alias */
RecompReturn Menu_Main_M0X0(CpuState *cpu);
RecompReturn Menu_Main_M0X1(CpuState *cpu);
RecompReturn Menu_Main_M1X0(CpuState *cpu);
RecompReturn Menu_Main_M1X1(CpuState *cpu);
void Menu_Build(CpuState *cpu);  /* $03:8200 alias */
RecompReturn Menu_Build_M0X0(CpuState *cpu);
RecompReturn Menu_Build_M0X1(CpuState *cpu);
RecompReturn Menu_Build_M1X0(CpuState *cpu);
RecompReturn Menu_Build_M1X1(CpuState *cpu);
void Menu_Zone(CpuState *cpu);  /* $03:8400 alias */
RecompReturn Menu_Zone_M0X0(CpuState *cpu);
RecompReturn Menu_Zone_M0X1(CpuState *cpu);
RecompReturn Menu_Zone_M1X0(CpuState *cpu);
RecompReturn Menu_Zone_M1X1(CpuState *cpu);
void Menu_Query(CpuState *cpu);  /* $03:8600 alias */
RecompReturn Menu_Query_M0X0(CpuState *cpu);
RecompReturn Menu_Query_M0X1(CpuState *cpu);
RecompReturn Menu_Query_M1X0(CpuState *cpu);
RecompReturn Menu_Query_M1X1(CpuState *cpu);
void Menu_Budget(CpuState *cpu);  /* $03:8800 alias */
RecompReturn Menu_Budget_M0X0(CpuState *cpu);
RecompReturn Menu_Budget_M0X1(CpuState *cpu);
RecompReturn Menu_Budget_M1X0(CpuState *cpu);
RecompReturn Menu_Budget_M1X1(CpuState *cpu);
void Menu_Disaster(CpuState *cpu);  /* $03:8A00 alias */
RecompReturn Menu_Disaster_M0X0(CpuState *cpu);
RecompReturn Menu_Disaster_M0X1(CpuState *cpu);
RecompReturn Menu_Disaster_M1X0(CpuState *cpu);
RecompReturn Menu_Disaster_M1X1(CpuState *cpu);
void Menu_Scenario(CpuState *cpu);  /* $03:8C00 alias */
RecompReturn Menu_Scenario_M0X0(CpuState *cpu);
RecompReturn Menu_Scenario_M0X1(CpuState *cpu);
RecompReturn Menu_Scenario_M1X0(CpuState *cpu);
RecompReturn Menu_Scenario_M1X1(CpuState *cpu);
void Menu_Options(CpuState *cpu);  /* $03:8E00 alias */
RecompReturn Menu_Options_M0X0(CpuState *cpu);
RecompReturn Menu_Options_M0X1(CpuState *cpu);
RecompReturn Menu_Options_M1X0(CpuState *cpu);
RecompReturn Menu_Options_M1X1(CpuState *cpu);
void Font_Draw(CpuState *cpu);  /* $03:9000 alias */
RecompReturn Font_Draw_M0X0(CpuState *cpu);
RecompReturn Font_Draw_M0X1(CpuState *cpu);
RecompReturn Font_Draw_M1X0(CpuState *cpu);
RecompReturn Font_Draw_M1X1(CpuState *cpu);
void Text_Print(CpuState *cpu);  /* $03:9200 alias */
RecompReturn Text_Print_M0X0(CpuState *cpu);
RecompReturn Text_Print_M0X1(CpuState *cpu);
RecompReturn Text_Print_M1X0(CpuState *cpu);
RecompReturn Text_Print_M1X1(CpuState *cpu);
void Number_Draw(CpuState *cpu);  /* $03:9400 alias */
RecompReturn Number_Draw_M0X0(CpuState *cpu);
RecompReturn Number_Draw_M0X1(CpuState *cpu);
RecompReturn Number_Draw_M1X0(CpuState *cpu);
RecompReturn Number_Draw_M1X1(CpuState *cpu);
void Panel_Budget(CpuState *cpu);  /* $03:9600 alias */
RecompReturn Panel_Budget_M0X0(CpuState *cpu);
RecompReturn Panel_Budget_M0X1(CpuState *cpu);
RecompReturn Panel_Budget_M1X0(CpuState *cpu);
RecompReturn Panel_Budget_M1X1(CpuState *cpu);
void Panel_Population(CpuState *cpu);  /* $03:9800 alias */
RecompReturn Panel_Population_M0X0(CpuState *cpu);
RecompReturn Panel_Population_M0X1(CpuState *cpu);
RecompReturn Panel_Population_M1X0(CpuState *cpu);
RecompReturn Panel_Population_M1X1(CpuState *cpu);
void Panel_RCI(CpuState *cpu);  /* $03:9A00 alias */
RecompReturn Panel_RCI_M0X0(CpuState *cpu);
RecompReturn Panel_RCI_M0X1(CpuState *cpu);
RecompReturn Panel_RCI_M1X0(CpuState *cpu);
RecompReturn Panel_RCI_M1X1(CpuState *cpu);
void Panel_Map(CpuState *cpu);  /* $03:9C00 alias */
RecompReturn Panel_Map_M0X0(CpuState *cpu);
RecompReturn Panel_Map_M0X1(CpuState *cpu);
RecompReturn Panel_Map_M1X0(CpuState *cpu);
RecompReturn Panel_Map_M1X1(CpuState *cpu);
void Input_Read(CpuState *cpu);  /* $04:8000 alias */
RecompReturn Input_Read_M0X0(CpuState *cpu);
RecompReturn Input_Read_M0X1(CpuState *cpu);
RecompReturn Input_Read_M1X0(CpuState *cpu);
RecompReturn Input_Read_M1X1(CpuState *cpu);
void Input_Process(CpuState *cpu);  /* $04:8100 alias */
RecompReturn Input_Process_M0X0(CpuState *cpu);
RecompReturn Input_Process_M0X1(CpuState *cpu);
RecompReturn Input_Process_M1X0(CpuState *cpu);
RecompReturn Input_Process_M1X1(CpuState *cpu);
void Joypad_Read(CpuState *cpu);  /* $04:8200 alias */
RecompReturn Joypad_Read_M0X0(CpuState *cpu);
RecompReturn Joypad_Read_M0X1(CpuState *cpu);
RecompReturn Joypad_Read_M1X0(CpuState *cpu);
RecompReturn Joypad_Read_M1X1(CpuState *cpu);
void Mouse_Read(CpuState *cpu);  /* $04:8300 alias */
RecompReturn Mouse_Read_M0X0(CpuState *cpu);
RecompReturn Mouse_Read_M0X1(CpuState *cpu);
RecompReturn Mouse_Read_M1X0(CpuState *cpu);
RecompReturn Mouse_Read_M1X1(CpuState *cpu);
void Cursor_Update(CpuState *cpu);  /* $04:8400 alias */
RecompReturn Cursor_Update_M0X0(CpuState *cpu);
RecompReturn Cursor_Update_M0X1(CpuState *cpu);
RecompReturn Cursor_Update_M1X0(CpuState *cpu);
RecompReturn Cursor_Update_M1X1(CpuState *cpu);
void Cursor_Draw(CpuState *cpu);  /* $04:8500 alias */
RecompReturn Cursor_Draw_M0X0(CpuState *cpu);
RecompReturn Cursor_Draw_M0X1(CpuState *cpu);
RecompReturn Cursor_Draw_M1X0(CpuState *cpu);
RecompReturn Cursor_Draw_M1X1(CpuState *cpu);
void Tool_Select(CpuState *cpu);  /* $04:8600 alias */
RecompReturn Tool_Select_M0X0(CpuState *cpu);
RecompReturn Tool_Select_M0X1(CpuState *cpu);
RecompReturn Tool_Select_M1X0(CpuState *cpu);
RecompReturn Tool_Select_M1X1(CpuState *cpu);
void Tool_Execute(CpuState *cpu);  /* $04:8700 alias */
RecompReturn Tool_Execute_M0X0(CpuState *cpu);
RecompReturn Tool_Execute_M0X1(CpuState *cpu);
RecompReturn Tool_Execute_M1X0(CpuState *cpu);
RecompReturn Tool_Execute_M1X1(CpuState *cpu);
void SPC_Upload(CpuState *cpu);  /* $05:8000 alias */
RecompReturn SPC_Upload_M0X0(CpuState *cpu);
RecompReturn SPC_Upload_M0X1(CpuState *cpu);
RecompReturn SPC_Upload_M1X0(CpuState *cpu);
RecompReturn SPC_Upload_M1X1(CpuState *cpu);
void SPC_Command(CpuState *cpu);  /* $05:8100 alias */
RecompReturn SPC_Command_M0X0(CpuState *cpu);
RecompReturn SPC_Command_M0X1(CpuState *cpu);
RecompReturn SPC_Command_M1X0(CpuState *cpu);
RecompReturn SPC_Command_M1X1(CpuState *cpu);
void SPC_Read(CpuState *cpu);  /* $05:8200 alias */
RecompReturn SPC_Read_M0X0(CpuState *cpu);
RecompReturn SPC_Read_M0X1(CpuState *cpu);
RecompReturn SPC_Read_M1X0(CpuState *cpu);
RecompReturn SPC_Read_M1X1(CpuState *cpu);
void Music_Play(CpuState *cpu);  /* $05:8300 alias */
RecompReturn Music_Play_M0X0(CpuState *cpu);
RecompReturn Music_Play_M0X1(CpuState *cpu);
RecompReturn Music_Play_M1X0(CpuState *cpu);
RecompReturn Music_Play_M1X1(CpuState *cpu);
void Music_Stop(CpuState *cpu);  /* $05:8400 alias */
RecompReturn Music_Stop_M0X0(CpuState *cpu);
RecompReturn Music_Stop_M0X1(CpuState *cpu);
RecompReturn Music_Stop_M1X0(CpuState *cpu);
RecompReturn Music_Stop_M1X1(CpuState *cpu);
void Music_Fade(CpuState *cpu);  /* $05:8500 alias */
RecompReturn Music_Fade_M0X0(CpuState *cpu);
RecompReturn Music_Fade_M0X1(CpuState *cpu);
RecompReturn Music_Fade_M1X0(CpuState *cpu);
RecompReturn Music_Fade_M1X1(CpuState *cpu);
void SFX_Play(CpuState *cpu);  /* $05:8600 alias */
RecompReturn SFX_Play_M0X0(CpuState *cpu);
RecompReturn SFX_Play_M0X1(CpuState *cpu);
RecompReturn SFX_Play_M1X0(CpuState *cpu);
RecompReturn SFX_Play_M1X1(CpuState *cpu);
void SFX_Update(CpuState *cpu);  /* $05:8700 alias */
RecompReturn SFX_Update_M0X0(CpuState *cpu);
RecompReturn SFX_Update_M0X1(CpuState *cpu);
RecompReturn SFX_Update_M1X0(CpuState *cpu);
RecompReturn SFX_Update_M1X1(CpuState *cpu);
void LC_LZ5_Decompress(CpuState *cpu);  /* $06:8000 alias */
RecompReturn LC_LZ5_Decompress_M0X0(CpuState *cpu);
RecompReturn LC_LZ5_Decompress_M0X1(CpuState *cpu);
RecompReturn LC_LZ5_Decompress_M1X0(CpuState *cpu);
RecompReturn LC_LZ5_Decompress_M1X1(CpuState *cpu);
void LC_LZ5_Decode(CpuState *cpu);  /* $06:8200 alias */
RecompReturn LC_LZ5_Decode_M0X0(CpuState *cpu);
RecompReturn LC_LZ5_Decode_M0X1(CpuState *cpu);
RecompReturn LC_LZ5_Decode_M1X0(CpuState *cpu);
RecompReturn LC_LZ5_Decode_M1X1(CpuState *cpu);
void RLE_Decompress(CpuState *cpu);  /* $06:8400 alias */
RecompReturn RLE_Decompress_M0X0(CpuState *cpu);
RecompReturn RLE_Decompress_M0X1(CpuState *cpu);
RecompReturn RLE_Decompress_M1X0(CpuState *cpu);
RecompReturn RLE_Decompress_M1X1(CpuState *cpu);
void Map_Decompress(CpuState *cpu);  /* $06:8600 alias */
RecompReturn Map_Decompress_M0X0(CpuState *cpu);
RecompReturn Map_Decompress_M0X1(CpuState *cpu);
RecompReturn Map_Decompress_M1X0(CpuState *cpu);
RecompReturn Map_Decompress_M1X1(CpuState *cpu);
void Scenario_Decompress(CpuState *cpu);  /* $06:8800 alias */
RecompReturn Scenario_Decompress_M0X0(CpuState *cpu);
RecompReturn Scenario_Decompress_M0X1(CpuState *cpu);
RecompReturn Scenario_Decompress_M1X0(CpuState *cpu);
RecompReturn Scenario_Decompress_M1X1(CpuState *cpu);
void Title_Init(CpuState *cpu);  /* $07:8000 alias */
RecompReturn Title_Init_M0X0(CpuState *cpu);
RecompReturn Title_Init_M0X1(CpuState *cpu);
RecompReturn Title_Init_M1X0(CpuState *cpu);
RecompReturn Title_Init_M1X1(CpuState *cpu);
void Title_Draw(CpuState *cpu);  /* $07:8200 alias */
RecompReturn Title_Draw_M0X0(CpuState *cpu);
RecompReturn Title_Draw_M0X1(CpuState *cpu);
RecompReturn Title_Draw_M1X0(CpuState *cpu);
RecompReturn Title_Draw_M1X1(CpuState *cpu);
void Title_Update(CpuState *cpu);  /* $07:8400 alias */
RecompReturn Title_Update_M0X0(CpuState *cpu);
RecompReturn Title_Update_M0X1(CpuState *cpu);
RecompReturn Title_Update_M1X0(CpuState *cpu);
RecompReturn Title_Update_M1X1(CpuState *cpu);
void Title_Input(CpuState *cpu);  /* $07:8600 alias */
RecompReturn Title_Input_M0X0(CpuState *cpu);
RecompReturn Title_Input_M0X1(CpuState *cpu);
RecompReturn Title_Input_M1X0(CpuState *cpu);
RecompReturn Title_Input_M1X1(CpuState *cpu);
void Logo_Draw(CpuState *cpu);  /* $07:8800 alias */
RecompReturn Logo_Draw_M0X0(CpuState *cpu);
RecompReturn Logo_Draw_M0X1(CpuState *cpu);
RecompReturn Logo_Draw_M1X0(CpuState *cpu);
RecompReturn Logo_Draw_M1X1(CpuState *cpu);
void Stars_Draw(CpuState *cpu);  /* $07:8A00 alias */
RecompReturn Stars_Draw_M0X0(CpuState *cpu);
RecompReturn Stars_Draw_M0X1(CpuState *cpu);
RecompReturn Stars_Draw_M1X0(CpuState *cpu);
RecompReturn Stars_Draw_M1X1(CpuState *cpu);
void Skyline_Draw(CpuState *cpu);  /* $07:8C00 alias */
RecompReturn Skyline_Draw_M0X0(CpuState *cpu);
RecompReturn Skyline_Draw_M0X1(CpuState *cpu);
RecompReturn Skyline_Draw_M1X0(CpuState *cpu);
RecompReturn Skyline_Draw_M1X1(CpuState *cpu);
void Cutscene_Play(CpuState *cpu);  /* $07:8E00 alias */
RecompReturn Cutscene_Play_M0X0(CpuState *cpu);
RecompReturn Cutscene_Play_M0X1(CpuState *cpu);
RecompReturn Cutscene_Play_M1X0(CpuState *cpu);
RecompReturn Cutscene_Play_M1X1(CpuState *cpu);

/* Hand-written non-recompiled bodies still declared here.
 * These are not produced by the v2 emit pipeline but are
 * referenced by recompiled code via funcs.h.
 */
void ResetSpritesFunc(int wh);
void RunOneFrameOfGame_Internal(void);

/* Watchdog hook called at every block label. Implemented in
 * snesrecomp/runner/src/common_cpu_infra.c.
 */
void WatchdogCheck(void);
