#!/usr/bin/env python3
"""Ingest the SimCity SNES disassembly as an authority for recomp/*.cfg.

WHY THIS EXISTS

`recomp/bank02.cfg` declares VRAM tile indices as functions (`func Res_D01_TL
0x03AC`), and all 41 bank-02 nodes in `src/gen/program_manifest.json` come
back with `instruction_count: 0`. `bank03.cfg`-`bank07.cfg` declare round
addresses with descriptive names that no analysis could have produced. None of
the 8 cfg files contain a single `data_region`, `symbol` or `name` directive -
against 748 / 6817 / 82 in SuperMarioWorldRecomp.

The cause is that the cfgs were written by hand, by guesswork, from a
different source. There is no need to guess: **Yoshifanatic1's
SimCity-SNES-Disassembly reassembles byte-identical to our ROM** (md5
23715fc7ef700b3999384d5be20f4db5, 524288 bytes, checksum $39B3 restored,
framework pinned at V1.0.1, asar 1.91). SuperMarioWorldRecomp ingests
SMWDisX exactly this way and treats it as an *authority*, not a reference - the
property that makes it usable is that it assembles to the same bytes, so every
label in it is provably a label in our ROM.

This script imports that vocabulary:

  name         every CODE_* / DATA_* label, so $009311 becomes a name in
               every log and a reviewer reads the game's own vocabulary
  symbol       every !RAM_SIMC_* constant from RAM_Map_SIMC.asm, so $7E:0B53
               prints as CurrentYear instead of a hex offset. This is the
               directive that ends the "which address is the date" question -
               that field was not found in three weeks of WRAM diffing
  data_region  every DATA_* label that is incbin-backed or %FREE_BYTES filler,
               so bank-02's zero-instruction nodes acquire real extents

Nothing asset-shaped crosses over: the disassembly repository contains no
graphics, palettes or audio, and this script emits only labels and addresses.
That satisfies the project's zero-asset-distribution rule.

COPYRIGHT AND PROVENANCE

The disassembly is third-party work and is NOT vendored into this repository.
Point --disassembly at your own clone. The output is derived metadata - a
label and an address - which is the same category of thing `funcs.h` already
carries, and it is what makes the cfg files reviewable by someone who has not
cloned the disassembly.

WHAT THIS DOES NOT DO

It does not merge upstream's 147 commits, and it does not touch the emulator.
Both are separate changes with separate verification. Do them one at a time.

Usage:
    tools/ingest_simcitydis.py --disassembly /path/to/SimCity-SNES-Disassembly
    tools/ingest_simcitydis.py --disassembly ... --dry-run
"""
import argparse
import os
import re
import sys
from collections import defaultdict

# LoROM banks 00-07 are what the disassembly's ROM map declares for this ROM
# (ExLoROM_Memory_Map.asm: !BANK_00 = 00 .. !BANK_07 = 07, and
# ROM_Map_SIMC_U.asm calls %SIMCBank00Macros(!BANK_00, !BANK_00) through
# %SIMCBank07Macros(!BANK_07, !BANK_0F)).
BANKS = ["00", "01", "02", "03", "04", "05", "06", "07"]

# macro SIMCBankNNMacros(StartBank, EndBank) -> labels belong to that bank
MACRO_RE = re.compile(r"^macro\s+SIMCBank(\d{2})Macros\(", re.MULTILINE)
LABEL_RE = re.compile(r"^(CODE_[0-9A-Fa-f]{6}|DATA_[0-9A-Fa-f]{6}):")
# !RAM_SIMC_City_CurrentYearLo = $000B53
RAM_RE = re.compile(r"^!([A-Za-z0-9_]+)\s*=\s*\$([0-9A-Fa-f]{4,6})\s*$")
# %FREE_BYTES($02FCEC, 788, $FF) / incbin "path"
FREE_RE = re.compile(r"%FREE_BYTES\(\s*\$([0-9A-Fa-f]{2,6})")
INCBIN_RE = re.compile(r'^\s*incbin\s+"([^"]+)"', re.MULTILINE)

BANNER = """\
# >>> BEGIN disassembly overlay (SimCity-SNES-Disassembly, Yoshifanatic1)
# Generated by tools/ingest_simcitydis.py. DO NOT HAND-EDIT.
#
# Authority: that disassembly reassembles byte-identical to the ROM this
# project targets (md5 23715fc7ef700b3999384d5be20f4db5, 524288 bytes,
# checksum $39B3 restored; framework pinned at V1.0.1, asar 1.91). That is the
# property that makes a label from it a fact about our ROM rather than a
# guess. Labels and addresses only - no assets cross over.
#
# %d names, %d symbols, %d data regions across banks %s.
# Re-run the ingestor rather than editing; edits here are lost.
# <<< END
"""


def split_banks(text):
    """Return {bank: [(addr16, name, kind), ...]} from the routine macro file."""
    starts = [(int(m.group(1), 16), m.start()) for m in MACRO_RE.finditer(text)]
    out = defaultdict(list)
    for i, (bank, start) in enumerate(starts):
        end = starts[i + 1][1] if i + 1 < len(starts) else len(text)
        body = text[start:end]
        for line in body.split("\n"):
            m = LABEL_RE.match(line)
            if m:
                name = m.group(1)
                addr = int(name.split("_")[1], 16)
                kind = "code" if name.startswith("CODE_") else "data"
                out["%02X" % bank].append((addr, name, kind))
    return out


def ram_symbols(path):
    """{bank: [(addr, name), ...]} from RAM_Map_SIMC.asm.

    Addresses there are 16-bit and wrap: $0B53 is $7E:0B53, but $8000+ is
    $7F:xxxx (battery SRAM). The $7E/$7F split is decided by the high bit.
    """
    out = defaultdict(list)
    for line in open(path, encoding="utf-8", errors="replace"):
        m = RAM_RE.match(line)
        if not m:
            continue
        name, hexaddr = m.group(1), int(m.group(2), 16)
        if hexaddr >= 0x8000:
            bank = "SRAM"          # $7F - battery backed, and the city lives here
        else:
            bank = "00"             # $7E - WRAM
        out[bank].append((hexaddr, name))
    return out


def data_regions(text):
    """DATA_* labels that are incbin-backed or %FREE_BYTES filler.

    Only these are marked data. A DATA_ label that is followed by real code is
    left alone, because marking it data would tell the decoder to stop at a
    label that is in fact code - and `DISASSEMBLY.md:65-73` in the SMW project
    documents exactly that trap: adding data_regions alone dropped 62 real
    instruction boundaries from the emitted program.
    """
    regions = set()
    lines = text.split("\n")
    for i, line in enumerate(lines):
        m = LABEL_RE.match(line)
        if not m or not m.group(1).startswith("DATA_"):
            continue
        # look ahead a few lines for a body that is not code
        for follow in lines[i + 1:i + 6]:
            s = follow.strip()
            if not s or s.startswith(";") or s.startswith("%") or s.startswith("}"):
                continue
            if s.startswith("incbin") or s.startswith("%FREE_BYTES") \
               or s.startswith("db ") or s.startswith("dw ") or s.startswith("dl "):
                regions.add(int(m.group(1).split("_")[1], 16))
            break
    return regions


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--disassembly", required=True,
                    help="path to a clone of Yoshifanatic1/SimCity-SNES-Disassembly")
    ap.add_argument("--out", default="recomp",
                    help="output directory (default: recomp)")
    ap.add_argument("--dry-run", action="store_true",
                    help="report what would be written and change nothing")
    args = ap.parse_args()

    routines = os.path.join(args.disassembly, "SIMC", "Routine_Macros_SIMC.asm")
    rammap = os.path.join(args.disassembly, "SIMC", "RAM_Map_SIMC.asm")
    srammap = os.path.join(args.disassembly, "SIMC", "SRAM_Map_SIMC.asm")
    for p in (routines, rammap):
        if not os.path.isfile(p):
            print("error: %s not found - is --disassembly pointing at the repo root?"
                  % p, file=sys.stderr)
            return 2

    text = open(routines, encoding="utf-8", errors="replace").read()
    banks = split_banks(text)
    data = data_regions(text)

    ram = ram_symbols(rammap)
    sram = defaultdict(list)
    if os.path.isfile(srammap):
        sram = ram_symbols(srammap)

    total_names = sum(len(v) for v in banks.values())
    total_syms = sum(len(v) for v in ram.values()) + sum(len(v) for v in sram.values())
    total_regions = len(data)
    print("== SimCity disassembly ingest ==")
    print("  source      : %s" % args.disassembly)
    print("  labels      : %d" % total_names)
    print("  RAM symbols : %d  (%d WRAM/$7E, %d SRAM/$7F)"
          % (total_syms, sum(len(v) for v in ram.values()),
             sum(len(v) for v in sram.values())))
    print("  data regions: %d" % total_regions)
    for b in BANKS:
        print("    bank %s: %d labels" % (b, len(banks.get(b, []))))

    if args.dry_run:
        print("\n(dry run - nothing written)")
        return 0

    banner = BANNER % (total_names, total_syms, total_regions,
                       ", ".join(b for b in BANKS if banks.get(b)))

    for b in BANKS:
        entries = sorted(banks.get(b, []))
        if not entries:
            continue
        path = os.path.join(args.out, "bank%s.cfg" % b)
        with open(path, "a", encoding="utf-8") as f:
            f.write("\n" + banner)
            f.write("\n")
            for addr, name, kind in entries:
                if kind == "data" and addr in data:
                    # data_region <bank> <start> <end> - four tokens. The bank
                    # is a separate argument (cfg_loader.py:788), and the
                    # region runs to the next label so the decoder stops at
                    # the real boundary rather than at a guessed one.
                    nxt = next((a for a, _, _ in entries if a > addr), None)
                    end = (nxt - 1) if nxt is not None else (addr | 0xFFFF)
                    f.write("data_region 0x%s 0x%04X 0x%04X  # %s\n"
                            % (b, addr & 0xFFFF, end & 0xFFFF, name))
                else:
                    f.write("name 0x%s %s\n" % (addr, name))
        print("  wrote %s (%d lines)" % (path, len(entries)))

    # WRAM and SRAM symbols go into the bank-00 cfg: they are addresses in the
    # $7E/$7F spaces, not in any ROM bank, and the cfg schema has no separate
    # place for them. They are emitted as comments so they are readable in
    # every log without pretending to be code addresses.
    p0 = os.path.join(args.out, "bank00.cfg")
    with open(p0, "a", encoding="utf-8") as f:
        f.write("\n# >>> BEGIN RAM map overlay (generated, do not hand-edit)\n")
        f.write("# $7E:xxxx  WRAM          $7F:xxxx  battery SRAM (the city lives here)\n")
        for addr, name in sorted(ram.get("00", [])):
            f.write("#   $7E:%04X  %s\n" % (addr, name))
        for addr, name in sorted(sram.get("SRAM", [])):
            f.write("#   $7F:%04X  %s\n" % (addr | 0x8000, name))
        f.write("# <<< END\n")
    print("  wrote %s (RAM map as comments)" % p0)
    print("\nNext: bash tools/regen.sh --rom \"$PWD/SimCity (USA).sfc\"")
    print("Then: make test && make test-rom && make perf")
    print("make clock is expected to stay red - a change there is not progress.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
